import type { Metadata } from "next";
import "../globals.css";
import PublicNavbar from "@/components/public/PublicNavbar";
import PublicFooter from "@/components/public/PublicFooter";

export const metadata: Metadata = {
  title: "Bouquet by Dila",
  description: "Generated by create next app",
};

export default function PembeliLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <PublicNavbar />
      <div className="min-h-screen">
        {children}
      </div>
      <PublicFooter />
    </>
  );
}
